### ISSUE TITLE
Question on while loop logic. 

### ISSUE THREAD

**Issue by StrikeForceZero** [qwirk/veryslowpidhax#1]
Looking at the while loop, I see this opens a process, checks the pid then closes the process. While running this I see the same pid displayed throughout the lifetime of this app.

Is the goal of this:

* to increment the PID? If so, then shouldn't this open multiple processes before closing them? 
* to overflow the PID to rollover to 0? Or is this targeting any given PID specified?

**Comment by StrikeForceZero** [comment]
Sorry if you got a notification with a blank issue was on mobile, and accidentally clicked open before typing.

**Comment by StrikeForceZero** [comment]
Actually answered most of my questions from looking at the comments in https://github.com/toiry921/StuPIDSlowHAX/blob/master/source/main.c

Still not sure how this is supposed to work with the PID remaining the same each iteration.

**Comment by qwirk** [comment]
Basically yes it overflows the PID
